using System;
using System.Collections.Generic;
using CSWarfront.Core;
using UnityEngine;

namespace CSWarfront.Game.Models
{
    /// <summary>
    /// Builds, at runtime, a Unity multi-submesh Mesh plus an array of per-submesh materials colored
    /// from the .mtl, out of the ObjData parsed by Core (Task69; a trimmed-down port of
    /// MissileDisaster.Game.Models.MissileMeshBuilder.TryBuild). The only caller is
    /// <see cref="WarfrontModelProvider.TryGetModel"/> (the unit default-model resolution path, see
    /// <see cref="UnitMeshSource"/>).
    /// Task82: the single-submesh merged variant TryBuildMergedMesh (used only for bases, i.e. the
    /// cloned electricity-tab prefab WarfrontBasePrefab) was deleted because the cloned-prefab
    /// mechanism itself was fully removed and it had no callers left.
    /// Mesh creation is only allowed on Unity's main thread, so always call this from the main thread
    /// (the same thread that creates the GameObjects).
    /// </summary>
    internal static class WarfrontMeshBuilder
    {
        /// <summary>
        /// Task69: maps each ObjData submesh (one per usemtl block in the .obj) directly to a Unity
        /// submesh, and creates one home-made Standard-shader material per submesh painted with the
        /// .mtl's Kd color (a direct port of MissileDisaster.Game.Models.MissileMeshBuilder.TryBuild;
        /// no behavior change, only the namespace differs).
        /// The caller (<see cref="WarfrontModelProvider.TryGetModel"/>) does the caching, so this
        /// method only builds and does not cache.
        /// </summary>
        public static bool TryBuild(ObjData obj, Dictionary<string, MtlColor> mtl, Color fallbackColor, out Mesh mesh, out Material[] materials)
        {
            mesh = null;
            materials = null;

            try
            {
                if (obj == null || obj.Positions == null || obj.Submeshes == null) return false;
                int vertexCount = obj.VertexCount;
                if (vertexCount <= 0 || obj.Submeshes.Count == 0) return false;

                var vertices = new Vector3[vertexCount];
                for (int i = 0; i < vertexCount; i++)
                {
                    vertices[i] = new Vector3(
                        obj.Positions[i * 3],
                        obj.Positions[i * 3 + 1],
                        obj.Positions[i * 3 + 2]);
                }

                var builtMesh = new Mesh();
                builtMesh.vertices = vertices;
                builtMesh.subMeshCount = obj.Submeshes.Count;

                var mats = new Material[obj.Submeshes.Count];

                for (int s = 0; s < obj.Submeshes.Count; s++)
                {
                    ObjSubmesh sub = obj.Submeshes[s];
                    List<int> validTriangles = FilterValidTriangles(sub != null ? sub.Triangles : null, vertexCount);
                    builtMesh.SetTriangles(validTriangles, s);
                    mats[s] = BuildMaterial(sub != null ? sub.Material : null, mtl, fallbackColor);
                }

                builtMesh.RecalculateNormals();
                builtMesh.RecalculateBounds();

                mesh = builtMesh;
                materials = mats;
                return true;
            }
            catch (Exception e)
            {
                ModConfig.LogError("WarfrontMeshBuilder.TryBuild error: " + e);
                mesh = null;
                materials = null;
                return false;
            }
        }

        /// <summary>Removes corrupt/out-of-range triangle indices. Unity's SetTriangles throws when an
        /// index is out of range, so triangles must always pass through this filter first.</summary>
        private static List<int> FilterValidTriangles(List<int> triangles, int vertexCount)
        {
            if (triangles == null || triangles.Count == 0) return new List<int>();

            var valid = new List<int>(triangles.Count);
            for (int i = 0; i + 2 < triangles.Count; i += 3)
            {
                int a = triangles[i];
                int b = triangles[i + 1];
                int c = triangles[i + 2];
                if (a < 0 || a >= vertexCount) continue;
                if (b < 0 || b >= vertexCount) continue;
                if (c < 0 || c >= vertexCount) continue;

                valid.Add(a);
                valid.Add(b);
                valid.Add(c);
            }
            return valid;
        }

        /// <summary>Task69: port of MissileMeshBuilder.BuildMaterial. Paints one submesh's .mtl color
        /// onto a home-made Standard-shader material. Uses fallbackColor when materialName is missing
        /// from the .mtl or mtl itself is null (models generated by tools/gen_models.py always ship
        /// with an .mtl even for single-color models, so this fallback is theoretical only — in
        /// practice the .mtl's Kd always hits).</summary>
        private static Material BuildMaterial(string materialName, Dictionary<string, MtlColor> mtl, Color fallbackColor)
        {
            Material mat = CreateBaseMaterial();
            if (mat == null) return null;

            try
            {
                float r = fallbackColor.r, g = fallbackColor.g, b = fallbackColor.b;

                MtlColor found;
                if (mtl != null && !string.IsNullOrEmpty(materialName) && mtl.TryGetValue(materialName, out found) && found != null)
                {
                    r = found.R;
                    g = found.G;
                    b = found.B;
                }

                Color color = new Color(r, g, b, 1f);
                mat.color = color;
                if (mat.HasProperty("_Color")) mat.SetColor("_Color", color);
                if (mat.HasProperty("_Metallic")) mat.SetFloat("_Metallic", ModConfig.ObjMetallic);
                if (mat.HasProperty("_Glossiness")) mat.SetFloat("_Glossiness", ModConfig.ObjGlossiness);
            }
            catch (Exception e)
            {
                ModConfig.LogError("WarfrontMeshBuilder.BuildMaterial error: " + e);
            }

            return mat;
        }

        private static Material CreateBaseMaterial()
        {
            try
            {
                Shader shader = Shader.Find("Standard");
                if (shader == null) shader = Shader.Find("Legacy Shaders/Diffuse");
                if (shader == null) shader = Shader.Find("Diffuse");
                if (shader == null) return null;
                return new Material(shader);
            }
            catch (Exception e)
            {
                ModConfig.LogError("WarfrontMeshBuilder.CreateBaseMaterial error: " + e);
                return null;
            }
        }
    }
}
